# command line arguments
action = 'action'
username = 'username'
password = 'password'
location = 'location'
role = 'role'
price = 'price'
start = 'start'
end = 'end'
energy = 'energy'
signup = 'signup'
update_settings = 'update_settings'
view_settings = 'view_settings'
supplier = 'supplier'
buyer = 'buyer'
history = 'history'
meter_id = 'meter_id'
